# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np
from numpy import random

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [32]:
# Method 1
a= np.random.rand(2,3,5)
print(a)

[[[0.92911156 0.10032606 0.43052531 0.48299236 0.33827747]
  [0.5009917  0.11170864 0.24927132 0.81847132 0.29913978]
  [0.63600051 0.44018041 0.00359881 0.80852635 0.6192038 ]]

 [[0.52828593 0.51862848 0.47349592 0.65695571 0.27086794]
  [0.7617272  0.4340031  0.71867607 0.75720703 0.77705934]
  [0.87099217 0.58062624 0.92927037 0.40757974 0.33374976]]]


In [68]:
# Method 2
a = np.random.randint(1,10,(2,3,5))
print(a)

[[[1 8 4 9 7]
  [5 4 3 6 3]
  [1 6 9 6 9]]

 [[2 3 5 1 8]
  [5 7 4 5 7]
  [6 3 7 4 6]]]


In [66]:
# Method 3
a = np.random.random((2,3,5))
print(a)

[[[0.42018778 0.39406505 0.93770654 0.92059417 0.50630507]
  [0.59279079 0.99008758 0.61197251 0.49447939 0.35396226]
  [0.74903925 0.66477955 0.27224927 0.27703897 0.19070795]]

 [[0.17258038 0.08005416 0.92750039 0.40204785 0.96405668]
  [0.6521573  0.10332205 0.63531764 0.14640438 0.73524923]
  [0.56221241 0.71717666 0.64351077 0.60093579 0.63818552]]]


#### 4. Print *a*.


In [ ]:
# your code here
print(a)

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [7]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print(np.array_equal(a,b))

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
print(np.add(a,b))
# they don't have the same structure

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [37]:
# your code/answer here
d = (np.add(a,c))
# they have the same structure

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [38]:
# your code/answer here
print(a)
print(d)
#"d" is the same as "a+1"

[[[0.92911156 0.10032606 0.43052531 0.48299236 0.33827747]
  [0.5009917  0.11170864 0.24927132 0.81847132 0.29913978]
  [0.63600051 0.44018041 0.00359881 0.80852635 0.6192038 ]]

 [[0.52828593 0.51862848 0.47349592 0.65695571 0.27086794]
  [0.7617272  0.4340031  0.71867607 0.75720703 0.77705934]
  [0.87099217 0.58062624 0.92927037 0.40757974 0.33374976]]]
[[[1.92911156 1.10032606 1.43052531 1.48299236 1.33827747]
  [1.5009917  1.11170864 1.24927132 1.81847132 1.29913978]
  [1.63600051 1.44018041 1.00359881 1.80852635 1.6192038 ]]

 [[1.52828593 1.51862848 1.47349592 1.65695571 1.27086794]
  [1.7617272  1.4340031  1.71867607 1.75720703 1.77705934]
  [1.87099217 1.58062624 1.92927037 1.40757974 1.33374976]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [42]:
# your code/answer here
print(np.array_equal(e,a))
#Yes, because you multiply it by one.

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [53]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [57]:
# your code here
f = np.empty((2, 3, 5))
f

array([[[1.92911156, 1.10032606, 1.43052531, 1.48299236, 1.33827747],
        [1.5009917 , 1.11170864, 1.24927132, 1.81847132, 1.29913978],
        [1.63600051, 1.44018041, 1.00359881, 1.80852635, 1.6192038 ]],

       [[1.52828593, 1.51862848, 1.47349592, 1.65695571, 1.27086794],
        [1.7617272 , 1.4340031 , 1.71867607, 1.75720703, 1.77705934],
        [1.87099217, 1.58062624, 1.92927037, 1.40757974, 1.33374976]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here